generate_data: introduce argument client to replace 6 others
instructlab/sdg pull request #114
Opened 2024-07-11 15:20 UTC by makelinux

Number of generate_data argument became very big.
It is need to factor the code to keep to code clean and observable.

After updating CLI and replacing six arguments
api_base, api_key, tls_insecure, tls_client_cert, tls_client_key, tls_client_passwd with single `client` argument remove that six arguments from generate_data().

2024-07-18 14:08 UTC, hickeyma requested changes
@makelinux Do you mind updating the title and description of the PR to more accurately describe the changes. The description doesn't seem to align with the changes.

2024-07-19 10:04 UTC, markmc commented
Note - overlaps with #113 and see also [this comment from @tiran](https://github.com/instructlab/instructlab/pull/1649#issuecomment-2221266846)

2024-07-19 16:06 UTC, makelinux commented
> Note - overlaps with #113 and see also [this comment from @tiran](https://github.com/instructlab/instructlab/pull/1649#issuecomment-2221266846)

Thank you, the same motivation.
The advantages of my PR:
1. ready to merge (without conflicts)
2. provides temporary compatibility with current CLI.
3. Single small commit. (Long commits are difficult to review)

2024-07-22 13:09 UTC, derekhiggins approved these changes
going with this version as its simpler, doesn't introduce another API and is ready to merge.

2024-07-22 15:49 UTC, russellb commented
@hickeyma want to take another look?

2024-07-24 07:51 UTC, merged