tests: Add unit tests
instructlab/sdg pull request #188
Opened 2024-07-23 14:39 UTC by hickeyma

Add unit tests for taxonomy and model family.

2024-07-25 10:23 UTC, markmc requested changes
Thanks @hickeyma just a couple of comments on the taxonomy test

2024-07-25 10:23 UTC, markmc commented on tests/taxonomy.py
> +    def remove_file(self, rel_path: str) -> None:
this is unused?

2024-07-26 10:25 UTC, hickeyma commented on tests/test_taxonomy.py
> +        self.taxonomy.add_tracked(tracked_file)
Good idea, updated to pass contents.

2024-07-26 10:26 UTC, hickeyma commented on tests/test_taxonomy.py
> +        assert TEST_VALID_COMPOSITIONAL_SKILL_YAML not in leaf_node
yes, changed

2024-07-26 10:26 UTC, hickeyma commented on tests/taxonomy.py
> +    def remove_file(self, rel_path: str) -> None:
Good catch, removed.

2024-07-26 10:28 UTC, hickeyma commented on tests/taxonomy.py
> +            file_path.write_text(TEST_VALID_COMPOSITIONAL_SKILL_YAML, encoding="utf-8")
Sure, makes sense.

2024-07-26 10:28 UTC, hickeyma commented
Thanks for review @markmc. Updated and ready for review again.

2024-07-26 16:26 UTC, markmc approved these changes
Thanks, @hickeyma !

2024-07-26 16:27 UTC, merged