ci: move E2E runner from github to AWS
instructlab/sdg pull request #260
Opened 2024-08-29 13:00 UTC by nathan-weinberg

Resolves https://github.com/instructlab/sdg/issues/250

2024-08-29 13:14 UTC, alimaredia commented
@nathan-weinberg can you send a run triggered by hand that shows that these new runners work?

2024-08-29 13:18 UTC, nathan-weinberg commented
> @nathan-weinberg can you send a run triggered by hand that shows that these new runners work?

I have no way of doing that, you can looking at the Training implementation for reference

2024-08-30 15:28 UTC, danmcp requested changes

2024-08-30 15:28 UTC, danmcp commented on .github/workflows/e2e-nvidia-t4-x1.yml
> +      - name: Run e2e test
Needs `working-directory: ./instructlab`

2024-08-30 15:28 UTC, danmcp commented on .github/workflows/e2e-nvidia-t4-x1.yml
> +          . ./instructlab/venv/bin/activate
Should be: `. ../instructlab/venv/bin/activate`

2024-08-30 15:33 UTC, danmcp commented on .github/workflows/e2e-nvidia-t4-x1.yml
> +          ./instructlab/scripts/basic-workflow-tests.sh -m
And this one `./scripts/basic-workflow-tests.sh -m`

2024-08-30 17:31 UTC, danmcp approved these changes

2024-08-30 18:11 UTC, khaledsulayman approved these changes

2024-08-30 18:21 UTC, merged