ci: update lint workflow
instructlab/sdg pull request #278
Opened 2024-09-13 16:57 UTC by nathan-weinberg

aligns moreso with updated CLI implementation
adds missing job that mergify expects
hardens runner and other steps

2024-09-13 18:52 UTC, bjhargrave requested changes

2024-09-13 18:52 UTC, bjhargrave commented on .github/workflows/lint.yml
> +            commands:
```suggestion
            commands: |
```

2024-09-13 19:38 UTC, bjhargrave approved these changes

2024-09-17 01:52 UTC, bbrowning approved these changes
I compared this to what's in the CLI repo's lint.yml and it looks good. Thanks for keeping these in-sync!

2024-09-17 02:02 UTC, merged