Update URLs in `docs/dataset_formats.md` to point to the new InstructLab `scripts/test-data` files
instructlab/sdg pull request #448
Opened 2024-12-11 16:38 UTC by courtneypacheco

The `scripts/test-data` directory structure was modified in the [instructlab/instructlab](https://github.com/instructlab/instructlab) repo to accommodate more skill + knowledge files, which means we need to update the `scripts/test-data` URLs in `docs/dataset_formats.md` accordingly.

2024-12-11 18:08 UTC, courtneypacheco commented on docs/dataset_formats.md
> +* Compositional skills
I was wondering that too, especially if we start adding even more YAMLs over time. (Could make for a lengthy list.)

Also, the new sub-directory names are pretty self explanatory IMO.

I'm open to either approach

2025-01-16 15:26 UTC, bbrowning requested changes
Just a small issue with one broken link we should fix, but thanks for updating this!

Longer-term I'd like to probably just link to the core or taxonomy repos for any/all discussion of the taxonomy format, but that is probably best done once we move preprocessing out of SDG.

2025-01-28 20:01 UTC, bbrowning approved these changes

2025-01-28 20:02 UTC, bbrowning commented
I pushed one more commit to fix the broken link - otherwise looks good to me, and merging this one. Thanks for the contribution!

2025-01-28 20:02 UTC, merged