Implement initial CI integrations
instructlab/sdg pull request #7
Opened 2024-06-03 19:26 UTC by nathan-weinberg

Resolves #4 

This PR implements the following CI integrations:
- **Dependabot** via a GitHub Action configuration
- **Markdown Linting** implemented via `Makefile` as well as a Hardened GitHub Action
- **Spellchecking** implemented via `tox` (with a `Makefile` entrypoint) as well as a Hardened GitHub Action
- **Action Linting** implemented via `Makefile` as well as a Hardened GitHub Action
- **Python Linting and Formatting** via `tox` using `ruff` and `isort` (with a `Makefile` entrypoint)

It also addresses Markdown and Python linting errors that are now being detected

2024-06-03 19:34 UTC, 2chiefk approved these changes

2024-06-03 21:48 UTC, russellb commented
Let me know when this is ready for review.

2024-06-04 10:16 UTC, bjhargrave requested changes
Otherwise LGTM

2024-06-04 10:16 UTC, bjhargrave commented on .github/dependabot.yml
> +      interval: "daily"
```suggestion
```

These lines don't apply in this repo.

2024-06-04 13:27 UTC, nathan-weinberg commented on .github/dependabot.yml
> +      interval: "daily"
Ah good catch! Fixed

2024-06-04 13:29 UTC, nathan-weinberg commented
> Let me know when this is ready for review.

This should be good to go - can't test the actions themselves in this PR but everything other than Dependabot can be run locally

2024-06-04 13:29 UTC, nathan-weinberg commented
I can squash commits if desired, left them separated for easier reviewing since this is a fairly large PR

2024-06-04 14:17 UTC, bjhargrave approved these changes

2024-06-04 14:51 UTC, russellb approved these changes

2024-06-04 14:51 UTC, merged